"""empty message

Revision ID: 264017c3ed58
Revises: 5c9c586d144b
Create Date: 2016-10-14 00:52:47.433772

"""

# revision identifiers, used by Alembic.
revision = '264017c3ed58'
down_revision = '5c9c586d144b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'updated_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###
