"""empty message

Revision ID: 88d56ea8eab4
Revises: 9837220b57bd
Create Date: 2016-09-27 21:00:50.233685

"""

# revision identifiers, used by Alembic.
revision = '88d56ea8eab4'
down_revision = '9837220b57bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmark', ['title'])
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_column('user', 'email')
    op.drop_constraint(None, 'bookmark', type_='unique')
    ### end Alembic commands ###
