"""empty message

Revision ID: 91f956e5b859
Revises: cef0957f4422
Create Date: 2016-09-28 20:11:31.960668

"""

# revision identifiers, used by Alembic.
revision = '91f956e5b859'
down_revision = 'cef0957f4422'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_id_title_url', 'bookmark', ['user_id', 'title', 'url'])
    op.drop_index('title', table_name='bookmark')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'bookmark', ['title'], unique=True)
    op.drop_constraint('unique_user_id_title_url', 'bookmark', type_='unique')
    ### end Alembic commands ###
