"""empty message

Revision ID: 9585568b8c79
Revises: 88d56ea8eab4
Create Date: 2016-09-27 21:02:24.333224

"""

# revision identifiers, used by Alembic.
revision = '9585568b8c79'
down_revision = '88d56ea8eab4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmark', 'title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('bookmark', 'url',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('bookmark', 'url',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('bookmark', 'title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    ### end Alembic commands ###
