"""empty message

Revision ID: 9837220b57bd
Revises: e24e7e86b187
Create Date: 2016-09-26 21:49:14.359134

"""

# revision identifiers, used by Alembic.
revision = '9837220b57bd'
down_revision = 'e24e7e86b187'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('title', sa.String(length=200), nullable=True))
    op.drop_column('bookmark', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('bookmark', 'title')
    ### end Alembic commands ###
