"""empty message

Revision ID: e24e7e86b187
Revises: 545c434f0a3a
Create Date: 2016-09-26 21:48:10.123515

"""

# revision identifiers, used by Alembic.
revision = 'e24e7e86b187'
down_revision = '545c434f0a3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
